name: Node.js CI

on:
  workflow_dispatch:
  release:
    types: [ published, prereleased, released ]
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  TARGET_DEV: ${{ github.ref_name == github.event.repository.default_branch }}
  TARGET_TEST_OR_PROD: contains(fromJson('["created", "prereleased", "released"]'), github.event.action) )
  TARGET_TEST: ${{ github.event.release != null && contains(fromJson('["created", "prereleased", "released"]'), github.event.action) ) && github.event.release.prerelease }}
  TARGET_PROD: ${{ github.event.release != null && contains(fromJson('["created", "prereleased", "released"]'), github.event.action) ) && !github.event.release.prerelease }}

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: |
          if [[ $TARGET_PROD = true ]]; then 
            ./build.sh prod; 
          elif [[ $TARGET_TEST = true ]]; then 
            ./build.sh test; 
          else 
            ./build.sh dev; 
          fi
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  publish:
    needs: build
    if: ${{ env.TARGET_DEV || env.TARGET_TEST_OR_PROD }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - run: npm ci
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/cbush06/patient-portal
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch && github.event.release == null }}
            type=semver,pattern={{raw}},suffix=-RC,enable=${{ github.event.release != null && github.event.release.prerelease == true }}
            type=semver,pattern={{raw}},enable=${{ github.event.release != null && github.event.release.prerelease == false }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
